include:
  - src.zip
kind: ArchiveUploadSpec
name: src-zip-Gt2V

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: func-iptv-0ba4a0ab-ea57-45db-a3fa-ff05345b77f6
  namespace: fission-function
spec:
  buildcmd: ./customBuild.sh
  deployment:
    checksum: {}
  environment:
    name: go
    namespace: fission-function
  source:
    checksum: {}
    type: url
    url: archive://src-zip-Gt2V
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-07-03T07:34:58Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: func-iptv
  namespace: fission-function
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: go
    namespace: fission-function
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: Handler
    packageref:
      name: func-iptv-0ba4a0ab-ea57-45db-a3fa-ff05345b77f6
      namespace: fission-function
  requestsPerPod: 1
  resources: {}
