apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: func-iptv
  namespace: fission
spec:
  createingress: true
  functionref:
    functionweights: null
    name: func-iptv
    type: name
  host: ""
  ingressconfig:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dongfg
    host: iptv.func.dongfg.com
    path: /
    tls: tls-iptv-func-dongfg
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /{Subpath}
